Finish
KushnirYuliya/social-page pull request #1
Opened 2021-11-09 12:39 UTC by KushnirYuliya

hello

2021-11-10 20:07 UTC, AliakseiYakubuk requested changes
1.Название пр это важная штука, назвпние должно отражать функционал который добовляется в этой ветке. "finish" ничего не говорит про это. Переименуй пр плз
2. Название коммита это не менее важная штука. Название коммита будет помогать ориентироваться по истории проекта. Далее, Все следующие коммиты называй нормально
3. Что бы не случилось, не мержи пр и не удаляй репозиторий)

2021-11-10 20:07 UTC, AliakseiYakubuk commented on sp.css
> +    color:black;
1. Используй [css variables](https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties#%D0%BF%D0%B5%D1%80%D0%B2%D1%8B%D0%B9_%D1%88%D0%B0%D0%B3_%D1%81_css_%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D0%BC%D0%B8)
2. Обьяви их в отдельном файле variables.css и подключи к html
3. Обычно цвета обьявляются по такой [схеме](https://mui.com/customization/palette/#default-values) плюс переменные для белого цвета и черного.
 Создай переменные с такими же названиями и не больше.
**Все** цвета в стилях должны быть заменены соотв. переменными.

2021-11-10 20:07 UTC, AliakseiYakubuk commented on sp.css
> +a{
Все общие стили ( для селекторов по элементу например, как здесь ) пиши перед классами , рядом со сттлями для body

2021-11-10 20:07 UTC, AliakseiYakubuk commented on sp.css
> +    font-size: 2.25em;
:+1:

2021-11-10 20:07 UTC, AliakseiYakubuk commented on sp.css
> +    filter: opacity(0.8);
`filter` тяжелое св во, изза него иногда страницы глючат
Здесь можно ```opacity: 0.8```

2021-11-10 20:07 UTC, AliakseiYakubuk commented on sp.css
> +@media screen and (max-width:767px){
1. Добавь 5  переменных для breakpoints с именами и значениями как [здесь](https://mui.com/customization/breakpoints/#default-breakpoints)
2. А можешь удалить `screen and`? Должно и так работать вроде

2021-11-10 20:07 UTC, AliakseiYakubuk commented on sp.css
> +    padding:0 15px;
Сделай плз красиво, все паддинги и марджины должны быть кратны 4, т.е. 4пх, 8пх, 12пх, 16пх, 20пх...
Если не сходится с дизайном , то ничего страшного

2021-11-10 20:07 UTC, AliakseiYakubuk commented on sp.html
> +        @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
Этот импорт надо переместить в css на самый верх

2021-11-10 20:07 UTC, AliakseiYakubuk commented on sp.html
> +        </div>
Наверное лишний div

2021-11-20 08:48 UTC, AliakseiYakubuk commented
Переименуй плз страницу в index.html -без этого деплой не будет работать

2021-12-07 08:20 UTC, KushnirYuliya commented on sp.html
> +        </div>
поправила оформление

2021-12-07 08:20 UTC, KushnirYuliya commented on sp.html
> +        @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
поправила, переместила в css

2021-12-07 08:26 UTC, KushnirYuliya commented on sp.css
> +    padding:0 15px;
исправила

2021-12-07 09:36 UTC, KushnirYuliya commented on sp.css
> +    filter: opacity(0.8);
сделала

2021-12-07 09:38 UTC, KushnirYuliya commented on sp.css
> +a{
сделала

2021-12-07 09:47 UTC, KushnirYuliya commented on sp.css
> +@media screen and (max-width:767px){
сделала, но боюсь неправильно поняла

2021-12-07 13:15 UTC, KushnirYuliya commented on sp.css
> +a{
сделала

2021-12-13 13:07 UTC, KushnirYuliya commented on sp.css
> +    color:black;
привет) наконец-то исправила)получилось

2021-12-15 07:55 UTC, AliakseiYakubuk commented on style.css
> +    filter: opacity(0.5);
`opacity: 0.5` здесь еще поправь плз

2021-12-15 08:11 UTC, AliakseiYakubuk commented on index.html
> +                <div class="form  color-gray">
Все элементы ввода данных (`input, select, textarea) должны находиться в теге `form`
Поправь плз `div` на `form`

2021-12-15 10:24 UTC, AliakseiYakubuk commented on index.html
> +                <div class="form  color-gray">
Все хорошо, но если на будущее лучше __всегда__ добавляй отступы к эклементам который вложены в другие элемент

2021-12-15 10:26 UTC, AliakseiYakubuk approved these changes

2021-12-15 10:29 UTC, merged